# Generated by Django 4.2.1 on 2023-05-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carblog', '0002_post_title_tag_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='treść',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tytuł',
        ),
    ]
